fix (anvil): error E0063 when compile on macOS
```
   Compiling anvil v0.2.0 (/Users/benji/Develop/blockchain/foundry/crates/anvil)
error[E0063]: missing fields `base_fee_per_blob_gas` and `blob_gas_used_ratio` in initializer of `alloy_rpc_types::FeeHistory`
    --> crates/anvil/src/eth/api.rs:1312:28
     |
1312 |         let mut response = FeeHistory {
     |                            ^^^^^^^^^^ missing `base_fee_per_blob_gas` and `blob_gas_used_ratio`

For more information about this error, try `rustc --explain E0063`.
error: could not compile `anvil` (lib) due to previous error
```